#!/bin/sh

out=Makefile
build=_build

echo "# This file was automatically generated by build-makefile.sh" > $out

test_files=`find . -name '*_test.v'`
targets=`basename --multiple $test_files | sed -e 's/^k12_//' -e 's/_test\.v$//'`

echo "SOURCES = \$(shell find . -type f -name '*.v')" >> $out
echo "all:" $targets >> $out

for target in $targets; do
    module="k12_"$target"_test"
    vvp=$build/$module.vvp
    csv=$build/$module.csv
    
    echo "$target: $csv" >> $out
    
    echo "$csv: $vvp" >> $out
    echo -e "\t$vvp > $csv" >> $out
    
    echo "$vvp: \${SOURCES}" >> $out
    echo -e "\tmkdir -p $build" >> $out
    echo -e "\tiverilog -o $vvp -s $module \${SOURCES}" >> $out
done

echo "clean:" >> $out
echo -e "\trm -rf $build" >> $out
