[DIP8]
pin_coords = [
    [0,  3], # 1
    [1,  3], # 2
    [2,  3], # 3
    [3,  3], # 4
    [3,  0], # 5
    [2,  0], # 6
    [1,  0], # 7
    [0,  0], # 8
]

[[DIP8.graphics]]
path = "M -0.5 -0.5 H 3.5 V 3.5 H -0.5 Z M -0.5 1 A 0.5 0.5 0 0 1 -0.5 2"
stroke = "000000"
stroke_width = 0.1
fill = "none"



[DIP14]
pin_coords = [
    [0,  3], # 1
    [1,  3], # 2
    [2,  3], # 3
    [3,  3], # 4
    [4,  3], # 5
    [5,  3], # 6
    [6,  3], # 7
    [6,  0], # 8
    [5,  0], # 9
    [4,  0], # 10
    [3,  0], # 11
    [2,  0], # 12
    [1,  0], # 13
    [0,  0], # 14
]

[[DIP14.graphics]]
path = "M -0.5 -0.5 H 6.5 V 3.5 H -0.5 Z M -0.5 1 A 0.5 0.5 0 0 1 -0.5 2"
stroke = "000000"
stroke_width = 0.1
fill = "none"



[DIP16]
pin_coords = [
    [0,  3], # 1
    [1,  3], # 2
    [2,  3], # 3
    [3,  3], # 4
    [4,  3], # 5
    [5,  3], # 6
    [6,  3], # 7
    [7,  3], # 8
    [7,  0], # 9
    [6,  0], # 10
    [5,  0], # 11
    [4,  0], # 12
    [3,  0], # 13
    [2,  0], # 14
    [1,  0], # 15
    [0,  0], # 16
]

[[DIP16.graphics]]
path = "M -0.5 -0.5 H 7.5 V 3.5 H -0.5 Z M -0.5 1 A 0.5 0.5 0 0 1 -0.5 2"
stroke = "000000"
stroke_width = 0.1
fill = "none"



[DIP20]
pin_coords = [
    [0,  3], # 1
    [1,  3], # 2
    [2,  3], # 3
    [3,  3], # 4
    [4,  3], # 5
    [5,  3], # 6
    [6,  3], # 7
    [7,  3], # 8
    [8,  3], # 9
    [9,  3], # 10
    [9,  0], # 11
    [8,  0], # 12
    [7,  0], # 13
    [6,  0], # 14
    [5,  0], # 15
    [4,  0], # 16
    [3,  0], # 17
    [2,  0], # 18
    [1,  0], # 19
    [0,  0], # 20
]

[[DIP20.graphics]]
path = "M -0.5 -0.5 H 9.5 V 3.5 H -0.5 Z M -0.5 1 A 0.5 0.5 0 0 1 -0.5 2"
stroke = "000000"
stroke_width = 0.1
fill = "none"



[WDIP28]
pin_coords = [
    [0,  6], # 1
    [1,  6], # 2
    [2,  6], # 3
    [3,  6], # 4
    [4,  6], # 5
    [5,  6], # 6
    [6,  6], # 7
    [7,  6], # 8
    [8,  6], # 9
    [9,  6], # 10
    [10, 6], # 11
    [11, 6], # 12
    [12, 6], # 13
    [13, 6], # 14
    [13, 0], # 15
    [12, 0], # 16
    [11, 0], # 17
    [10, 0], # 18
    [9,  0], # 19
    [8,  0], # 20
    [7,  0], # 21
    [6,  0], # 22
    [5,  0], # 23
    [4,  0], # 24
    [3,  0], # 25
    [2,  0], # 26
    [1,  0], # 27
    [0,  0], # 28
]

[[WDIP28.graphics]]
path = "M -0.5 -0.5 H 13.5 V 6.5 H -0.5 Z M -0.5 2.5 A 0.5 0.5 0 0 1 -0.5 3.5"
stroke = "000000"
stroke_width = 0.1
fill = "none"



[WDIP28_ZIF]
pin_coords = [
    [0,  6], # 1
    [1,  6], # 2
    [2,  6], # 3
    [3,  6], # 4
    [4,  6], # 5
    [5,  6], # 6
    [6,  6], # 7
    [7,  6], # 8
    [8,  6], # 9
    [9,  6], # 10
    [10, 6], # 11
    [11, 6], # 12
    [12, 6], # 13
    [13, 6], # 14
    [13, 0], # 15
    [12, 0], # 16
    [11, 0], # 17
    [10, 0], # 18
    [9,  0], # 19
    [8,  0], # 20
    [7,  0], # 21
    [6,  0], # 22
    [5,  0], # 23
    [4,  0], # 24
    [3,  0], # 25
    [2,  0], # 26
    [1,  0], # 27
    [0,  0], # 28
]

[[WDIP28_ZIF.graphics]]
path = "M -4 -1.5 H 16 V 7.5 H -4 Z M -4 2.5 A 0.5 0.5 0 0 1 -4 3.5"
stroke = "000000"
stroke_width = 0.1
fill = "none"
