[PADS2]
pin_coords = [
    [0, 0], # 1
    [1, 0], # 2
]



[PADS2_POLAR]
pin_coords = [
    [0, 0], # 1
    [1, 0], # 2
]

[[PADS2_POLAR.graphics]]
path = "M -0.4 0.5 h -1 m 0.5 0.5 v -1 M 1.4 0.5 h 1"
stroke = "000000"
stroke_width = 0.1
fill = "none"



[PADS6]
pin_coords = [
    [0, 0], # 1
    [1, 0], # 2
    [2, 0], # 3
    [3, 0], # 4
    [4, 0], # 5
    [5, 0], # 6
]



[PADS8]
pin_coords = [
    [0, 0], # 1
    [1, 0], # 2
    [2, 0], # 3
    [3, 0], # 4
    [4, 0], # 5
    [5, 0], # 6
    [6, 0], # 7
    [7, 0], # 8
]



[PADS10]
pin_coords = [
    [0, 0], # 1
    [1, 0], # 2
    [2, 0], # 3
    [3, 0], # 4
    [4, 0], # 5
    [5, 0], # 6
    [6, 0], # 7
    [7, 0], # 8
    [8, 0], # 9
    [9, 0], # 10
]



[PADS5X2]
pin_coords = [
    [0, 0], # 1
    [0, 1], # 2
    [1, 0], # 3
    [1, 1], # 4
    [2, 0], # 5
    [2, 1], # 6
    [3, 0], # 7
    [3, 1], # 8
    [4, 0], # 9
    [4, 1], # 10
]
