title = "EEPROM programmer Arduino shield"
min_x = -1
min_y = -1
max_x = 29
max_y = 22

[components]
  [components.U1]
    footprint = "WDIP28_ZIF"
    x = 12
    y = 6
    rotate = 0
    #x = 25
    #y = 12
    #rotate = 2
    label_x = 6.5
    label_y = 3.5
    label_hoz_anchor = "centre"

  [components.U2]
    footprint = "DIP20"
    #x = 16
    #y = 14
    #rotate = 0
    x = 20
    y = 17
    rotate = 2
    label_x = 4.5
    label_y = 2.0
    label_hoz_anchor = "centre"

  [components.U3]
    footprint = "DIP20"
    x = 7
    y = 11
    rotate = 1
    #x = 4
    #y = 20
    #rotate = 3
    label_x = 4.5
    label_y = 2.0
    label_hoz_anchor = "centre"

  [components.CONN1]
    footprint = "PADS8"
    x = 25
    y = 2
    rotate = 2
    label_x = 3.5
    label_y = 1.6
    label_hoz_anchor = "centre"

  [components.CONN2]
    footprint = "PADS10"
    x = 15
    y = 2
    rotate = 2
    label_x = 4.5
    label_y = 1.6
    label_hoz_anchor = "centre"

  [components.CONN3]
    footprint = "PADS6"
    x = 25
    y = 19
    rotate = 2
    label_x = 2.5
    label_y = -0.7
    label_hoz_anchor = "centre"

  [components.CONN4]
    footprint = "PADS8"
    x = 18
    y = 19
    rotate = 2
    label_x = 3.5
    label_y = -0.7
    label_hoz_anchor = "centre"

#[nets]
#  [nets.GND]
#    color = "000000"
#
#  [nets.Vcc]
#    color = "ff0000"

# Arduino shield outline
[[graphics]]
  path = "M 0 0 H 25.4 L 26 0.6 V 5.1 L 27 6.1 V 19 L 26 20 V 21 H 0 Z"
  stroke = "000000"
  stroke_width = 0.1
  fill = "ffffcc"

# Region in which component pins can be placed
[[graphics]]
  path = "M 8.5 3.5 H 25.5 V 8.5 H 24.5 V 11.5 H 25.5 V 16.5 H 24.5 V 17.5 H 10.5 V 18.5 H 9.5 V 20.5 H 0.5 V 10.5 H 8.5 Z"
  stroke = "none"
  fill = "ccccff"
[[graphics]]
  path = "M 12.5 9.5 H 20.5 V 11.5 H 12.5 Z"
  stroke = "none"
  fill = "ffffcc"
